language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install MySQL-python"

# command to run tests
script: 
  - python setup.py test
  # - runman.py script goes here to test manipulate
